//! Guest 26.1 public-export census. Generated from docs/ABI.md.
//! Not an Apple header. Selectors are IOConnect when present.

/// One confirmed public export.
#[derive(Clone, Copy, Debug)]
pub struct Export {
    pub name: &'static str,
    pub gpr: u8,
    pub fpr: u8,
    pub selector: Option<u32>,
    pub stub: bool,
}

/// All 153 public `IOMobileFramebuffer*` names. Status is confirmed.
pub const EXPORTS: &[Export] = &[
    Export { name: "IOMobileFramebufferAnnounceNextSwapTimestamp", gpr: 2, fpr: 0, selector: None, stub: false },
    Export { name: "IOMobileFramebufferCalibrationBegin", gpr: 1, fpr: 0, selector: Some(0x14), stub: false },
    Export { name: "IOMobileFramebufferCalibrationToolboxCommand", gpr: 6, fpr: 0, selector: None, stub: false },
    Export { name: "IOMobileFramebufferChangeFrameInfo", gpr: 2, fpr: 0, selector: Some(0x49), stub: false },
    Export { name: "IOMobileFramebufferCopyLayerDisplayedSurface", gpr: 3, fpr: 0, selector: Some(0x53), stub: false },
    Export { name: "IOMobileFramebufferCopyProperty", gpr: 2, fpr: 0, selector: None, stub: false },
    Export { name: "IOMobileFramebufferCreateDisplayList", gpr: 1, fpr: 0, selector: None, stub: false },
    Export { name: "IOMobileFramebufferCreateStatistics", gpr: 2, fpr: 0, selector: None, stub: false },
    Export { name: "IOMobileFramebufferDisableCRCNotifications", gpr: 1, fpr: 0, selector: Some(0x48), stub: false },
    Export { name: "IOMobileFramebufferDisableHotPlugDetectNotifications", gpr: 1, fpr: 0, selector: Some(0x48), stub: false },
    Export { name: "IOMobileFramebufferDisableNeedSwapNotifications", gpr: 1, fpr: 0, selector: Some(0x48), stub: false },
    Export { name: "IOMobileFramebufferDisablePowerNotifications", gpr: 1, fpr: 0, selector: Some(0x48), stub: false },
    Export { name: "IOMobileFramebufferDisableVSyncNotifications", gpr: 1, fpr: 0, selector: Some(0x48), stub: false },
    Export { name: "IOMobileFramebufferEnableCRCNotifications", gpr: 3, fpr: 0, selector: Some(0x48), stub: false },
    Export { name: "IOMobileFramebufferEnableDisableDithering", gpr: 2, fpr: 0, selector: Some(0x1e), stub: false },
    Export { name: "IOMobileFramebufferEnableDisableVideoPowerSavings", gpr: 2, fpr: 0, selector: Some(0x21), stub: false },
    Export { name: "IOMobileFramebufferEnableHotPlugDetectNotifications", gpr: 3, fpr: 0, selector: Some(0x48), stub: false },
    Export { name: "IOMobileFramebufferEnableMirroring", gpr: 3, fpr: 0, selector: Some(0x29), stub: false },
    Export { name: "IOMobileFramebufferEnableNeedSwapNotifications", gpr: 3, fpr: 0, selector: Some(0x48), stub: false },
    Export { name: "IOMobileFramebufferEnablePowerNotifications", gpr: 3, fpr: 0, selector: Some(0x48), stub: false },
    Export { name: "IOMobileFramebufferEnableStatistics", gpr: 2, fpr: 0, selector: Some(0xd), stub: false },
    Export { name: "IOMobileFramebufferEnableVSyncNotifications", gpr: 3, fpr: 0, selector: Some(0x48), stub: false },
    Export { name: "IOMobileFramebufferFactoryPortal", gpr: 2, fpr: 0, selector: Some(0x4b), stub: false },
    Export { name: "IOMobileFramebufferFrameInfo", gpr: 4, fpr: 0, selector: None, stub: false },
    Export { name: "IOMobileFramebufferGetBandwidth", gpr: 2, fpr: 0, selector: Some(0x73), stub: false },
    Export { name: "IOMobileFramebufferGetBlock", gpr: 6, fpr: 0, selector: Some(0xaa), stub: false },
    Export { name: "IOMobileFramebufferGetBrightnessControlCapabilities", gpr: 1, fpr: 0, selector: None, stub: false },
    Export { name: "IOMobileFramebufferGetBrightnessControlInfo", gpr: 2, fpr: 0, selector: None, stub: false },
    Export { name: "IOMobileFramebufferGetBufBlock", gpr: 6, fpr: 0, selector: Some(0xaa), stub: false },
    Export { name: "IOMobileFramebufferGetCRCNotifyMessageCount", gpr: 1, fpr: 0, selector: None, stub: false },
    Export { name: "IOMobileFramebufferGetCRCRunLoopSource", gpr: 1, fpr: 0, selector: None, stub: false },
    Export { name: "IOMobileFramebufferGetCanvasSizes", gpr: 3, fpr: 0, selector: None, stub: false },
    Export { name: "IOMobileFramebufferGetColorRemapMode", gpr: 2, fpr: 0, selector: Some(0x39), stub: false },
    Export { name: "IOMobileFramebufferGetCurrentAbsoluteTime", gpr: 2, fpr: 0, selector: Some(0x4d), stub: false },
    Export { name: "IOMobileFramebufferGetDigitalOutMode", gpr: 3, fpr: 0, selector: Some(0x40), stub: false },
    Export { name: "IOMobileFramebufferGetDigitalOutState", gpr: 2, fpr: 0, selector: Some(0x19), stub: false },
    Export { name: "IOMobileFramebufferGetDisplayArea", gpr: 2, fpr: 0, selector: Some(0x1d), stub: false },
    Export { name: "IOMobileFramebufferGetDisplaySize", gpr: 2, fpr: 0, selector: Some(0x8), stub: false },
    Export { name: "IOMobileFramebufferGetDotPitch", gpr: 2, fpr: 0, selector: Some(0x1c), stub: false },
    Export { name: "IOMobileFramebufferGetDotPitchFloat", gpr: 2, fpr: 0, selector: Some(0x5a), stub: false },
    Export { name: "IOMobileFramebufferGetFrameworkInfo", gpr: 1, fpr: 0, selector: None, stub: false },
    Export { name: "IOMobileFramebufferGetGammaTable", gpr: 2, fpr: 0, selector: Some(0x1b), stub: false },
    Export { name: "IOMobileFramebufferGetHDCPAuthenticationProtocol", gpr: 1, fpr: 0, selector: None, stub: false },
    Export { name: "IOMobileFramebufferGetHDCPDownstreamState", gpr: 2, fpr: 0, selector: Some(0x18), stub: false },
    Export { name: "IOMobileFramebufferGetHDCPRunLoopSource", gpr: 1, fpr: 0, selector: None, stub: false },
    Export { name: "IOMobileFramebufferGetHotPlugRunLoopSource", gpr: 1, fpr: 0, selector: None, stub: false },
    Export { name: "IOMobileFramebufferGetID", gpr: 2, fpr: 0, selector: Some(0x7), stub: false },
    Export { name: "IOMobileFramebufferGetLayerDefaultSurface", gpr: 3, fpr: 0, selector: Some(0x3), stub: false },
    Export { name: "IOMobileFramebufferGetLinkQuality", gpr: 2, fpr: 0, selector: Some(0x50), stub: false },
    Export { name: "IOMobileFramebufferGetMainDisplay", gpr: 1, fpr: 0, selector: None, stub: false },
    Export { name: "IOMobileFramebufferGetMatrix", gpr: 3, fpr: 0, selector: Some(0x36), stub: false },
    Export { name: "IOMobileFramebufferGetMirrorError", gpr: 2, fpr: 0, selector: None, stub: false },
    Export { name: "IOMobileFramebufferGetProtectionOptions", gpr: 2, fpr: 0, selector: Some(0x52), stub: false },
    Export { name: "IOMobileFramebufferGetPulseWidthMaximization", gpr: 2, fpr: 0, selector: None, stub: false },
    Export { name: "IOMobileFramebufferGetRunLoopSource", gpr: 2, fpr: 0, selector: None, stub: false },
    Export { name: "IOMobileFramebufferGetSecondaryDisplay", gpr: 1, fpr: 0, selector: None, stub: false },
    Export { name: "IOMobileFramebufferGetServiceObject", gpr: 1, fpr: 0, selector: None, stub: false },
    Export { name: "IOMobileFramebufferGetSupportedDigitalOutModes", gpr: 3, fpr: 0, selector: None, stub: false },
    Export { name: "IOMobileFramebufferGetTypeID", gpr: 0, fpr: 0, selector: None, stub: false },
    Export { name: "IOMobileFramebufferGetVSyncRunLoopSource", gpr: 1, fpr: 0, selector: None, stub: false },
    Export { name: "IOMobileFramebufferGetWirelessSurface", gpr: 3, fpr: 2, selector: None, stub: false },
    Export { name: "IOMobileFramebufferGetWirelessSurfaceWithOptions", gpr: 4, fpr: 2, selector: None, stub: false },
    Export { name: "IOMobileFramebufferHDCPGetReply", gpr: 3, fpr: 0, selector: Some(0x30), stub: false },
    Export { name: "IOMobileFramebufferHDCPSendRequest", gpr: 5, fpr: 0, selector: Some(0x2f), stub: false },
    Export { name: "IOMobileFramebufferInstallVirtualDisplay", gpr: 4, fpr: 0, selector: None, stub: false },
    Export { name: "IOMobileFramebufferInstallVirtualDisplays", gpr: 3, fpr: 0, selector: None, stub: false },
    Export { name: "IOMobileFramebufferIsMainDisplay", gpr: 2, fpr: 0, selector: Some(0x12), stub: false },
    Export { name: "IOMobileFramebufferKernelTests", gpr: 2, fpr: 0, selector: Some(0x38), stub: false },
    Export { name: "IOMobileFramebufferOpen", gpr: 4, fpr: 0, selector: None, stub: false },
    Export { name: "IOMobileFramebufferOpenByName", gpr: 2, fpr: 0, selector: None, stub: false },
    Export { name: "IOMobileFramebufferReadyForSwap", gpr: 3, fpr: 0, selector: None, stub: false },
    Export { name: "IOMobileFramebufferRelbufInfo", gpr: 4, fpr: 0, selector: None, stub: false },
    Export { name: "IOMobileFramebufferRequestPowerChange", gpr: 2, fpr: 0, selector: Some(0xc), stub: false },
    Export { name: "IOMobileFramebufferSPLCGetBrightness", gpr: 2, fpr: 0, selector: Some(0x43), stub: false },
    Export { name: "IOMobileFramebufferSPLCSetBrightness", gpr: 2, fpr: 0, selector: Some(0x42), stub: false },
    Export { name: "IOMobileFramebufferScheduleWithDispatchQueue", gpr: 3, fpr: 0, selector: Some(0x3), stub: false },
    Export { name: "IOMobileFramebufferSetAmmoliteStrength", gpr: 1, fpr: 1, selector: None, stub: false },
    Export { name: "IOMobileFramebufferSetBlock", gpr: 6, fpr: 0, selector: Some(0xaa), stub: false },
    Export { name: "IOMobileFramebufferSetBrightnessControlCallback", gpr: 3, fpr: 0, selector: None, stub: false },
    Export { name: "IOMobileFramebufferSetBrightnessCorrection", gpr: 2, fpr: 0, selector: Some(0x32), stub: false },
    Export { name: "IOMobileFramebufferSetCanvasSize", gpr: 1, fpr: 2, selector: Some(0x35), stub: false },
    Export { name: "IOMobileFramebufferSetClamshellState", gpr: 2, fpr: 0, selector: Some(0x59), stub: false },
    Export { name: "IOMobileFramebufferSetColorRemapMode", gpr: 2, fpr: 0, selector: Some(0x33), stub: false },
    Export { name: "IOMobileFramebufferSetContrast", gpr: 1, fpr: 1, selector: Some(0x11), stub: false },
    Export { name: "IOMobileFramebufferSetDebugFlags", gpr: 4, fpr: 0, selector: Some(0xf), stub: false },
    Export { name: "IOMobileFramebufferSetDigitalOutMode", gpr: 3, fpr: 0, selector: Some(0x17), stub: false },
    Export { name: "IOMobileFramebufferSetDisplayDevice", gpr: 2, fpr: 0, selector: Some(0x16), stub: false },
    Export { name: "IOMobileFramebufferSetDroppable", gpr: 2, fpr: 0, selector: None, stub: false },
    Export { name: "IOMobileFramebufferSetFlags", gpr: 4, fpr: 0, selector: Some(0xe), stub: false },
    Export { name: "IOMobileFramebufferSetGammaTable", gpr: 2, fpr: 0, selector: Some(0x11), stub: false },
    Export { name: "IOMobileFramebufferSetIdleBuffer", gpr: 3, fpr: 0, selector: None, stub: false },
    Export { name: "IOMobileFramebufferSetIdleBufferEvent", gpr: 6, fpr: 0, selector: None, stub: false },
    Export { name: "IOMobileFramebufferSetLine21Data", gpr: 2, fpr: 0, selector: Some(0x23), stub: false },
    Export { name: "IOMobileFramebufferSetMatrix", gpr: 3, fpr: 0, selector: Some(0x37), stub: false },
    Export { name: "IOMobileFramebufferSetMirrorContentRegion", gpr: 1, fpr: 4, selector: Some(0x2c), stub: false },
    Export { name: "IOMobileFramebufferSetParameter", gpr: 4, fpr: 0, selector: Some(0x44), stub: false },
    Export { name: "IOMobileFramebufferSetPreset", gpr: 2, fpr: 0, selector: Some(0x3d), stub: false },
    Export { name: "IOMobileFramebufferSetRenderingAngle", gpr: 2, fpr: 0, selector: Some(0x2b), stub: false },
    Export { name: "IOMobileFramebufferSetTVOutMode", gpr: 2, fpr: 0, selector: Some(0xa), stub: false },
    Export { name: "IOMobileFramebufferSetTVOutSignalType", gpr: 2, fpr: 0, selector: Some(0x10), stub: false },
    Export { name: "IOMobileFramebufferSetTwilightStrength", gpr: 1, fpr: 1, selector: None, stub: false },
    Export { name: "IOMobileFramebufferSetUnderrunColor", gpr: 2, fpr: 0, selector: Some(0x1f), stub: false },
    Export { name: "IOMobileFramebufferSetVideoDACGain", gpr: 1, fpr: 1, selector: Some(0x22), stub: false },
    Export { name: "IOMobileFramebufferSetWSSInfo", gpr: 3, fpr: 0, selector: Some(0xb), stub: false },
    Export { name: "IOMobileFramebufferSetWhiteOnBlackMode", gpr: 2, fpr: 0, selector: Some(0x13), stub: false },
    Export { name: "IOMobileFramebufferSupportedFrameInfo", gpr: 1, fpr: 0, selector: None, stub: false },
    Export { name: "IOMobileFramebufferSurfaceIsReplaceable", gpr: 4, fpr: 0, selector: Some(0x31), stub: false },
    Export { name: "IOMobileFramebufferSwapActiveRegion", gpr: 2, fpr: 4, selector: None, stub: false },
    Export { name: "IOMobileFramebufferSwapBegin", gpr: 2, fpr: 0, selector: Some(0x4), stub: false },
    Export { name: "IOMobileFramebufferSwapCancel", gpr: 2, fpr: 0, selector: Some(0x34), stub: false },
    Export { name: "IOMobileFramebufferSwapCancelAll", gpr: 1, fpr: 0, selector: Some(0x51), stub: false },
    Export { name: "IOMobileFramebufferSwapCancelAllGetCurrent", gpr: 2, fpr: 0, selector: Some(0x5c), stub: false },
    Export { name: "IOMobileFramebufferSwapDebugInfo", gpr: 3, fpr: 0, selector: None, stub: false },
    Export { name: "IOMobileFramebufferSwapDirtyRegion", gpr: 1, fpr: 4, selector: None, stub: false },
    Export { name: "IOMobileFramebufferSwapEnd", gpr: 1, fpr: 0, selector: Some(0x5), stub: false },
    Export { name: "IOMobileFramebufferSwapGetCurrent", gpr: 2, fpr: 0, selector: Some(0x5b), stub: false },
    Export { name: "IOMobileFramebufferSwapSecureLayer", gpr: 4, fpr: 4, selector: None, stub: false },
    Export { name: "IOMobileFramebufferSwapSetAmbientLux", gpr: 1, fpr: 1, selector: None, stub: false },
    Export { name: "IOMobileFramebufferSwapSetBackgroundColor", gpr: 1, fpr: 3, selector: None, stub: false },
    Export { name: "IOMobileFramebufferSwapSetBlit", gpr: 3, fpr: 8, selector: None, stub: false },
    Export { name: "IOMobileFramebufferSwapSetBrightness", gpr: 2, fpr: 1, selector: None, stub: false },
    Export { name: "IOMobileFramebufferSwapSetBrightnessLimit", gpr: 2, fpr: 1, selector: None, stub: false },
    Export { name: "IOMobileFramebufferSwapSetColorMatrix", gpr: 4, fpr: 0, selector: Some(0x45), stub: false },
    Export { name: "IOMobileFramebufferSwapSetColorRemapMode", gpr: 2, fpr: 0, selector: None, stub: false },
    Export { name: "IOMobileFramebufferSwapSetDisplayEdr", gpr: 2, fpr: 1, selector: None, stub: false },
    Export { name: "IOMobileFramebufferSwapSetDisplayEdrHeadroom", gpr: 1, fpr: 1, selector: None, stub: false },
    Export { name: "IOMobileFramebufferSwapSetEventSignal", gpr: 4, fpr: 0, selector: None, stub: false },
    Export { name: "IOMobileFramebufferSwapSetEventSignalOnGlass", gpr: 3, fpr: 0, selector: None, stub: false },
    Export { name: "IOMobileFramebufferSwapSetEventWait", gpr: 4, fpr: 0, selector: None, stub: false },
    Export { name: "IOMobileFramebufferSwapSetGainMap", gpr: 2, fpr: 0, selector: None, stub: false },
    Export { name: "IOMobileFramebufferSwapSetGammaTable", gpr: 2, fpr: 0, selector: None, stub: false },
    Export { name: "IOMobileFramebufferSwapSetICCCurve", gpr: 5, fpr: 0, selector: Some(0x33), stub: false },
    Export { name: "IOMobileFramebufferSwapSetICCMatrix", gpr: 4, fpr: 0, selector: Some(0x32), stub: false },
    Export { name: "IOMobileFramebufferSwapSetIndicatorBrightness", gpr: 2, fpr: 1, selector: None, stub: false },
    Export { name: "IOMobileFramebufferSwapSetIndicatorBrightnessLimit", gpr: 1, fpr: 1, selector: None, stub: false },
    Export { name: "IOMobileFramebufferSwapSetLayer", gpr: 6, fpr: 0, selector: None, stub: false },
    Export { name: "IOMobileFramebufferSwapSetLayerEDRCompensation", gpr: 3, fpr: 1, selector: None, stub: false },
    Export { name: "IOMobileFramebufferSwapSetParams", gpr: 4, fpr: 0, selector: None, stub: false },
    Export { name: "IOMobileFramebufferSwapSetPulseWidthMaximization", gpr: 2, fpr: 0, selector: None, stub: false },
    Export { name: "IOMobileFramebufferSwapSetSecureAnimation", gpr: 2, fpr: 0, selector: None, stub: false },
    Export { name: "IOMobileFramebufferSwapSetTimestamp", gpr: 2, fpr: 0, selector: None, stub: false },
    Export { name: "IOMobileFramebufferSwapSetTimestamps", gpr: 4, fpr: 0, selector: None, stub: false },
    Export { name: "IOMobileFramebufferSwapSetToneMapConfig", gpr: 3, fpr: 0, selector: Some(0x6b), stub: false },
    Export { name: "IOMobileFramebufferSwapSetUISubRegion", gpr: 0, fpr: 0, selector: None, stub: true },
    Export { name: "IOMobileFramebufferSwapSetVideoDestEdgeAlpha", gpr: 3, fpr: 0, selector: None, stub: false },
    Export { name: "IOMobileFramebufferSwapSignal", gpr: 1, fpr: 0, selector: None, stub: true },
    Export { name: "IOMobileFramebufferSwapSubtitleRegion", gpr: 3, fpr: 4, selector: None, stub: false },
    Export { name: "IOMobileFramebufferSwapUIEdgeBlendMode", gpr: 3, fpr: 1, selector: None, stub: false },
    Export { name: "IOMobileFramebufferSwapWait", gpr: 3, fpr: 0, selector: Some(0x6), stub: false },
    Export { name: "IOMobileFramebufferSwapWaitWithTimeout", gpr: 3, fpr: 1, selector: Some(0x6), stub: false },
    Export { name: "IOMobileFramebufferSwapWorkaroundSettings", gpr: 3, fpr: 0, selector: None, stub: false },
    Export { name: "IOMobileFramebufferUnscheduleFromDispatchQueue", gpr: 3, fpr: 0, selector: None, stub: false },
    Export { name: "IOMobileFramebufferWaitSurface", gpr: 1, fpr: 0, selector: None, stub: false },
];

pub fn export(name: &str) -> Option<&'static Export> {
    EXPORTS.iter().find(|e| e.name == name)
}

#[cfg(test)]
mod tests {
    #[test]
    fn census_matches_public_exports() {
        assert_eq!(super::EXPORTS.len(), crate::PUBLIC_EXPORTS.len());
        for (a, b) in super::EXPORTS.iter().zip(crate::PUBLIC_EXPORTS) {
            assert_eq!(a.name, *b);
        }
        assert!(super::export("IOMobileFramebufferSwapSetLayer").is_some());
        assert!(super::export("IOMobileFramebufferSwapSignal").unwrap().stub);
        assert!(super::export("IOMobileFramebufferSwapSetUISubRegion").unwrap().stub);
    }
}

